Traceback (most recent call last):
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/billydodds/.pyenv/versions/3.8.3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Define Test Stat Functions

# due to their sine wave-like shape, events have a larger range than non-events
def ts_range(x): 
    return np.max(x) - np.min(x)

# the range but using the middle half of the distribution to reduce influence from outliers
def ts_IQR(x): 
    return np.quantile(x, 0.75) - np.quantile(x, 0.25)

# events have high peaks due to their shape compared to non-events
def ts_abs_max(x): 
    return np.max(np.abs(x))

# non-events cross the zero line (x-axis) often due to noise, while events have long periods over/under the zero line
def ts_zero_crossings(x):
    return np.sum(x[0:-1]*x[1::] <= 0)

# Fourier transforms can distinguish between events and non-events due to 
def max_frequency(frame, samprate=10000):
    fs = samprate
    dt = 1/fs
    t = np.arange(0, (len(frame)*dt), dt)
    # Num samples
    N = len(frame)
    yf = fft(frame)
    xf = fftfreq(N, 1/fs)
    np.size(xf)
    np.size(t)
    f, t, Sxx = signal.spectrogram(frame, fs)
    maximum = np.max(Sxx)
    threshold = maximum/5;
    maximum_Freqs = np.amax(Sxx, 0) # max frequency for each time
    return np.amax(maximum_Freqs)

tfn_candidates = {"Range": ts_range,
                  "IQR": ts_IQR,
                  "SD": np.std,
                  "Absolute Max": ts_abs_max,
                  "Zero Crossings": ts_zero_crossings,
                  "Fourier": ts_max_frequency}


------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-1fbbe7e08c74>[0m in [0;36m<module>[0;34m[0m
[1;32m     39[0m                   [0;34m"Absolute Max"[0m[0;34m:[0m [0mts_abs_max[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     40[0m                   [0;34m"Zero Crossings"[0m[0;34m:[0m [0mts_zero_crossings[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 41[0;31m                   "Fourier": ts_max_frequency}
[0m[1;32m     42[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'ts_max_frequency' is not defined
NameError: name 'ts_max_frequency' is not defined

