Traceback (most recent call last):
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/billydodds/.pyenv/versions/3.8.3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/billydodds/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def load_data(path, fnames, scale_factor = 1, shift_factor = -512):
    waves = {}
    labels = {}
    for file in fnames:
        # Load in wave file
        samprate, wav_array = wavfile.read(path+file+".wav")
        wav_array = wav_array*scale_factor
        wav_array += shift_factor
        waves[file] = wav_array
        # Load in label file
        labels_dat = pd.read_csv(path+file+".txt", sep=",\t", skiprows=1)
        labels_dat.columns = ["label", "time"]
        labels_dat.label = ["L" if label == 1 else "R" for label in labels_dat.label]
        labels[file] = labels_dat
    print(f"Successfully loaded {len(waves)} wavefiles:")
    print("\n".join(sorted(waves.keys())))
    return waves, labels

fnames = ["data1", "data2", "data3", "data4", "data5", "data6", "data7", "data8"]

# Randomly select two files for the test set, remainder as training
test_files = np.random.choice(fnames, 2, replace=False)
training_files = list(set(fnames) - set(test_files))

# Training Data
waves, labels = load_data(
    IN_PATH, training_files, scale_factor = 1, shift_factor = -512)

# Test Data
test_waves, test_labels = load_data(
    IN_PATH, test_files, scale_factor = 1, shift_factor = -512)

# Define Sample Rate: 10,000 Hz
samprate = 10_000

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-2-a8397ba8da66>[0m in [0;36m<module>[0;34m[0m
[1;32m     24[0m [0;34m[0m[0m
[1;32m     25[0m [0;31m# Training Data[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 26[0;31m waves, labels = load_data(
[0m[1;32m     27[0m     IN_PATH, training_files, scale_factor = 1, shift_factor = -512)
[1;32m     28[0m [0;34m[0m[0m

[0;32m<ipython-input-2-a8397ba8da66>[0m in [0;36mload_data[0;34m(path, fnames, scale_factor, shift_factor)[0m
[1;32m      4[0m     [0;32mfor[0m [0mfile[0m [0;32min[0m [0mfnames[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m         [0;31m# Load in wave file[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m         [0msamprate[0m[0;34m,[0m [0mwav_array[0m [0;34m=[0m [0mwavfile[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mpath[0m[0;34m+[0m[0mfile[0m[0;34m+[0m[0;34m".wav"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m         [0mwav_array[0m [0;34m=[0m [0mwav_array[0m[0;34m*[0m[0mscale_factor[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m         [0mwav_array[0m [0;34m+=[0m [0mshift_factor[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.pyenv/versions/3.8.3/envs/phys/lib/python3.8/site-packages/scipy/io/wavfile.py[0m in [0;36mread[0;34m(filename, mmap)[0m
[1;32m    542[0m         [0mmmap[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m    543[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 544[0;31m         [0mfid[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0;34m'rb'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    545[0m [0;34m[0m[0m
[1;32m    546[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/stephanie/Desktop/Aqua10/Datasets/data/data8.wav'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/stephanie/Desktop/Aqua10/Datasets/data/data8.wav'

